/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  RFPFieldResponse,
  RFPRequest,
  RFPResponse,
  ReadRfpFieldsExplorerRfpFieldsGetParams,
  SearchRfpsEndpointExplorerRfpsGetParams
} from '../../types';

import { api } from '../../axios/mutator';



  export const getExplorer = () => {
/**
 * @summary Read Rfp Fields
 */
const readRfpFieldsExplorerRfpFieldsGet = (
    params?: ReadRfpFieldsExplorerRfpFieldsGetParams,
 ) => {
      return api<RFPFieldResponse[]>(
      {url: `/explorer/rfp-fields/`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Search Rfps Endpoint
 */
const searchRfpsEndpointExplorerRfpsGet = (
    params?: SearchRfpsEndpointExplorerRfpsGetParams,
 ) => {
      return api<RFPResponse[]>(
      {url: `/explorer/rfps/`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Add Rfp
 */
const addRfpExplorerRfpsPost = (
    rFPRequest: RFPRequest,
 ) => {
      return api<RFPResponse>(
      {url: `/explorer/rfps/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: rFPRequest
    },
      );
    }
  /**
 * @summary Search Rfps
 */
const searchRfpsExplorerSingleRfpRfpIdGet = (
    rfpId: number,
 ) => {
      return api<RFPResponse>(
      {url: `/explorer/single-rfp/${rfpId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Edit Rfp
 */
const editRfpExplorerRfpsRfpIdPut = (
    rfpId: number,
    rFPRequest: RFPRequest,
 ) => {
      return api<RFPResponse>(
      {url: `/explorer/rfps/${rfpId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: rFPRequest
    },
      );
    }
  return {readRfpFieldsExplorerRfpFieldsGet,searchRfpsEndpointExplorerRfpsGet,addRfpExplorerRfpsPost,searchRfpsExplorerSingleRfpRfpIdGet,editRfpExplorerRfpsRfpIdPut}};
export type ReadRfpFieldsExplorerRfpFieldsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getExplorer>['readRfpFieldsExplorerRfpFieldsGet']>>>
export type SearchRfpsEndpointExplorerRfpsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getExplorer>['searchRfpsEndpointExplorerRfpsGet']>>>
export type AddRfpExplorerRfpsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getExplorer>['addRfpExplorerRfpsPost']>>>
export type SearchRfpsExplorerSingleRfpRfpIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getExplorer>['searchRfpsExplorerSingleRfpRfpIdGet']>>>
export type EditRfpExplorerRfpsRfpIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getExplorer>['editRfpExplorerRfpsRfpIdPut']>>>
