/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  NotificationResponse,
  RefreshTokenRefreshTokenPostParams,
  Token,
  UserMeInfoResponse,
} from '../../types';

import { api } from '../../axios/mutator';

export const getAuthentication = () => {
  /**
   * @summary Login
   */
  /**
   * @summary Refresh Token
   */
  const refreshTokenRefreshTokenPost = (
    params: RefreshTokenRefreshTokenPostParams
  ) => {
    return api<Token>({ url: `/refresh-token`, method: 'POST', params });
  };
  /**
   * @summary Read Users Me
   */
  const readUsersMeUsersMeGet = () => {
    return api<UserMeInfoResponse>({ url: `/users/me`, method: 'GET' });
  };
  /**
   * @summary Read Users Me
   */
  const readUsersMeNotifMeGet = () => {
    return api<NotificationResponse[]>({ url: `/notif/me`, method: 'GET' });
  };
  return {
    refreshTokenRefreshTokenPost,
    readUsersMeUsersMeGet,
    readUsersMeNotifMeGet,
  };
};
export type RefreshTokenRefreshTokenPostResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getAuthentication>['refreshTokenRefreshTokenPost']
    >
  >
>;
export type ReadUsersMeUsersMeGetResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAuthentication>['readUsersMeUsersMeGet']>
  >
>;
export type ReadUsersMeNotifMeGetResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAuthentication>['readUsersMeNotifMeGet']>
  >
>;
