/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  ProjectResponse,
  ProposalResponse,
  ProposalUpdate,
  ReadProjectsSupervisorProjectsGetParams,
  ReadProposalsSupervisorProposalsGetParams,
  ReadReportsSupervisorReportsGetParams,
  ReportResponse,
  ReportUpdate,
} from '../../types';

import { api } from '../../axios/mutator';

export const getSupervisor = () => {
  /**
   * @summary Read Proposals
   */
  const readProposalsSupervisorProposalsGet = (
    params?: ReadProposalsSupervisorProposalsGetParams
  ) => {
    return api<ProposalResponse[]>({
      url: `/supervisor/proposals/`,
      method: 'GET',
      params,
    });
  };
  /**
   * @summary Read Proposal
   */
  const readProposalSupervisorProposalsProposalIdGet = (proposalId: number) => {
    return api<ProposalResponse>({
      url: `/supervisor/proposals/${proposalId}`,
      method: 'GET',
    });
  };
  /**
   * @summary Edit Proposal
   */
  const editProposalSupervisorProposalsProposalIdPut = (
    proposalId: number,
    proposalUpdate: ProposalUpdate
  ) => {
    return api<ProposalResponse>({
      url: `/supervisor/proposals/${proposalId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: proposalUpdate,
    });
  };
  /**
   * @summary Read Reports
   */
  const readReportsSupervisorReportsGet = (
    params?: ReadReportsSupervisorReportsGetParams
  ) => {
    return api<ReportResponse[]>({
      url: `/supervisor/reports/`,
      method: 'GET',
      params,
    });
  };
  /**
   * @summary Read Report
   */
  const readReportSupervisorReportsReportIdGet = (reportId: number) => {
    return api<ReportResponse>({
      url: `/supervisor/reports/${reportId}`,
      method: 'GET',
    });
  };
  /**
   * @summary Edit Report
   */
  const editReportSupervisorReportsReportIdPut = (
    reportId: number,
    reportUpdate: ReportUpdate
  ) => {
    return api<ReportResponse>({
      url: `/supervisor/reports/${reportId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: reportUpdate,
    });
  };
  /**
   * @summary Read Projects
   */
  const readProjectsSupervisorProjectsGet = (
    params?: ReadProjectsSupervisorProjectsGetParams
  ) => {
    return api<ProjectResponse[]>({
      url: `/supervisor/projects/`,
      method: 'GET',
      params,
    });
  };
  return {
    readProposalsSupervisorProposalsGet,
    readProposalSupervisorProposalsProposalIdGet,
    editProposalSupervisorProposalsProposalIdPut,
    readReportsSupervisorReportsGet,
    readReportSupervisorReportsReportIdGet,
    editReportSupervisorReportsReportIdPut,
    readProjectsSupervisorProjectsGet,
  };
};
export type ReadProposalsSupervisorProposalsGetResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSupervisor>['readProposalsSupervisorProposalsGet']
    >
  >
>;
export type ReadProposalSupervisorProposalsProposalIdGetResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSupervisor
      >['readProposalSupervisorProposalsProposalIdGet']
    >
  >
>;
export type EditProposalSupervisorProposalsProposalIdPutResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getSupervisor
      >['editProposalSupervisorProposalsProposalIdPut']
    >
  >
>;
export type ReadReportsSupervisorReportsGetResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSupervisor>['readReportsSupervisorReportsGet']
    >
  >
>;
export type ReadReportSupervisorReportsReportIdGetResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSupervisor>['readReportSupervisorReportsReportIdGet']
    >
  >
>;
export type EditReportSupervisorReportsReportIdPutResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSupervisor>['editReportSupervisorReportsReportIdPut']
    >
  >
>;
export type ReadProjectsSupervisorProjectsGetResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSupervisor>['readProjectsSupervisorProjectsGet']
    >
  >
>;
