/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { api } from '../../axios/mutator';

export const getSeed = () => {
  /**
   * @summary Add Proposal
   */
  const addProposalSeedSeedGet = () => {
    return api<unknown>({ url: `/seed/seed/`, method: 'GET' });
  };
  return { addProposalSeedSeedGet };
};
export type AddProposalSeedSeedGetResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSeed>['addProposalSeedSeedGet']>>
>;
