/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { RFPResponse } from './rFPResponse';
import type { UserInfoLimitedResponse } from './userInfoLimitedResponse';
import type { AllocateResponseProjectTitle } from './allocateResponseProjectTitle';
import type { AllocateResponseProjectDescription } from './allocateResponseProjectDescription';
import type { AllocateResponseMaster } from './allocateResponseMaster';

export interface AllocateResponse {
  id: number;
  creatorId: number;
  createdAt: string;
  rfp: RFPResponse;
  allocatedToUser: UserInfoLimitedResponse;
  projectTitle?: AllocateResponseProjectTitle;
  projectDescription?: AllocateResponseProjectDescription;
  master?: AllocateResponseMaster;
  state: string;
}
