/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BodyLoginTokenPostGrantType } from './bodyLoginTokenPostGrantType';
import type { BodyLoginTokenPostClientId } from './bodyLoginTokenPostClientId';
import type { BodyLoginTokenPostClientSecret } from './bodyLoginTokenPostClientSecret';

export interface BodyLoginTokenPost {
  grantType?: BodyLoginTokenPostGrantType;
  username: string;
  password: string;
  scope?: string;
  clientId?: BodyLoginTokenPostClientId;
  clientSecret?: BodyLoginTokenPostClientSecret;
}
