/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CommissionResponseFileId } from './commissionResponseFileId';

export interface CommissionResponse {
  id: number;
  title: string;
  comment: string;
  state: number;
  proposalId: number;
  userSupervisorId: number;
  userDiscovererId: number;
  fileId?: CommissionResponseFileId;
}
