/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { CommissionRequestFileId } from './commissionRequestFileId';

export interface CommissionRequest {
  title: string;
  comment: string;
  state: number;
  proposalId: number;
  userSupervisorId: number;
  userDiscovererId: number;
  fileId?: CommissionRequestFileId;
}
