/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { LogResponseUserName } from './logResponseUserName';
import type { LogResponseAct } from './logResponseAct';
import type { LogResponseCreatedAt } from './logResponseCreatedAt';

export interface LogResponse {
  id: number;
  userName?: LogResponseUserName;
  act?: LogResponseAct;
  createdAt?: LogResponseCreatedAt;
}
