/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserInfoLimitedResponse } from './userInfoLimitedResponse';
import type { ProposalResponse } from './proposalResponse';

export interface ProjectResponse {
  id: number;
  creatorId: number;
  createdAt: string;
  creator: UserInfoLimitedResponse;
  startAt: string;
  endAt: string;
  title: string;
  master: string;
  proposal: ProposalResponse;
  supervisor: UserInfoLimitedResponse;
  user: UserInfoLimitedResponse;
}
