/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProposalSingleResponseInput } from './proposalSingleResponseInput';
import type { UserInfoLimitedResponse } from './userInfoLimitedResponse';

export interface ProjectResponseInput {
  id: number;
  title: string;
  proposal: ProposalSingleResponseInput;
  supervisor: UserInfoLimitedResponse;
  discoverer: UserInfoLimitedResponse;
  master: UserInfoLimitedResponse;
  broker: UserInfoLimitedResponse;
}
