/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ProjectResponse {
  id: number;
  title: string;
  proposalId: number;
  userSupervisorId: number;
  userDiscovererId: number;
  userMasterId: number;
  userBrokerId: number;
  userUserId: number;
}
