/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProposalSingleResponseOutput } from './proposalSingleResponseOutput';
import type { UserInfoLimitedResponse } from './userInfoLimitedResponse';

export interface ProjectResponseOutput {
  id: number;
  title: string;
  proposal: ProposalSingleResponseOutput;
  supervisor: UserInfoLimitedResponse;
  discoverer: UserInfoLimitedResponse;
  master: UserInfoLimitedResponse;
  broker: UserInfoLimitedResponse;
}
