/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProposalRequestFileId } from './proposalRequestFileId';

export interface ProposalRequest {
  info: string;
  RFP_id: number;
  userId: number;
  state: number;
  comment: string;
  fileId?: ProposalRequestFileId;
}
