/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProposalResponseStartAt } from './proposalResponseStartAt';
import type { ProposalResponseEndAt } from './proposalResponseEndAt';
import type { ProposalResponseAllocateId } from './proposalResponseAllocateId';
import type { ProposalResponseSupervisorId } from './proposalResponseSupervisorId';
import type { UserInfoLimitedResponse } from './userInfoLimitedResponse';
import type { ProposalResponseFileId } from './proposalResponseFileId';
import type { ProposalResponseComment } from './proposalResponseComment';

export interface ProposalResponse {
  id: number;
  creatorId: number;
  createdAt: string;
  startAt: ProposalResponseStartAt;
  endAt: ProposalResponseEndAt;
  masterNameAndFamily: string;
  title: string;
  description: string;
  RFP_id: number;
  allocateId: ProposalResponseAllocateId;
  supervisorId: ProposalResponseSupervisorId;
  userId: number;
  creator: UserInfoLimitedResponse;
  fileId: ProposalResponseFileId;
  state: string;
  comment: ProposalResponseComment;
}
