/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProposalUserUpdateRequestInfo } from './proposalUserUpdateRequestInfo';
import type { ProposalUserUpdateRequestRFPId } from './proposalUserUpdateRequestRFPId';
import type { ProposalUserUpdateRequestFileId } from './proposalUserUpdateRequestFileId';

export interface ProposalUserUpdateRequest {
  info: ProposalUserUpdateRequestInfo;
  RFP_id: ProposalUserUpdateRequestRFPId;
  fileId: ProposalUserUpdateRequestFileId;
}
