/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ReadProposalsBrokerProposalsLikeGetParams = {
skip?: number;
limit?: number;
info?: string;
};
