/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ReportRequest {
  title: string;
  projectId: number;
  comment: string;
  filePdfId: number;
  fileDocxId: number;
  filePptxId: number;
  anouncedPercent: number;
}
