/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ReportResponse {
  id: number;
  info: string;
  projectId: number;
  comment: string;
  state: number;
}
