/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ReportResponseAcceptedPercent } from './reportResponseAcceptedPercent';
import type { ProjectResponse } from './projectResponse';

export interface ReportResponse {
  id: number;
  creatorId: number;
  createdAt: string;
  title: string;
  comment: string;
  state: string;
  anouncedPercent: number;
  acceptedPercent: ReportResponseAcceptedPercent;
  projectId: number;
  filePdfId: number;
  fileDocxId: number;
  filePptxId: number;
  project: ProjectResponse;
}
