/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectResponseInput } from './projectResponseInput';

export interface ReportRequest {
  info: string;
  project: ProjectResponseInput;
  comment: string;
  state: number;
}
