/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ReportResponse } from './reportResponse';

export interface ReportFileResponse {
  id: number;
  info: string;
  report: ReportResponse;
  fileId: number;
}
