/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectResponse } from './projectResponse';

export interface ReportResponse {
  id: number;
  info: string;
  project: ProjectResponse;
  comment: string;
  state: number;
  fileId: number;
}
