/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ReportRequest {
  info: string;
  projectId: number;
  comment: string;
  fileId: number;
  percent: number;
}
