/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserInfoLimitedResponse } from './userInfoLimitedResponse';
import type { RFPResponseFileId } from './rFPResponseFileId';
import type { RFPFieldResponse } from './rFPFieldResponse';

export interface RFPResponse {
  id: number;
  info: string;
  createdAt: string;
  creator: UserInfoLimitedResponse;
  creatorId: number;
  fileId?: RFPResponseFileId;
  RFP_field: RFPFieldResponse;
}
