/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SupervisorUpdateProposalCommissionFileId } from './supervisorUpdateProposalCommissionFileId';
import type { SupervisorUpdateProposalCommissionDateTime } from './supervisorUpdateProposalCommissionDateTime';

export interface SupervisorUpdateProposal {
  comment: string;
  supervisorId: number;
  commissionFileId?: SupervisorUpdateProposalCommissionFileId;
  commissionDateTime?: SupervisorUpdateProposalCommissionDateTime;
}
