/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserMeInfoResponseResumeFileId } from './userMeInfoResponseResumeFileId';
import type { UserMeInfoResponseAddress } from './userMeInfoResponseAddress';
import type { UserMeInfoResponsePhone } from './userMeInfoResponsePhone';
import type { UserMeInfoResponseSTATE } from './userMeInfoResponseSTATE';

export interface UserMeInfoResponse {
  id: number;
  username: string;
  fname: string;
  lname: string;
  fatherName: string;
  birth: string;
  resumeFileId?: UserMeInfoResponseResumeFileId;
  address?: UserMeInfoResponseAddress;
  phone?: UserMeInfoResponsePhone;
  active: boolean;
  userTypeId: number;
  state: UserMeInfoResponseSTATE;
}
