/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserMeInfoResponseResumeFileId } from './userMeInfoResponseResumeFileId';
import type { UserMeInfoResponseAddress } from './userMeInfoResponseAddress';
import type { UserMeInfoResponsePhone } from './userMeInfoResponsePhone';
import type { UserMeInfoResponseAllocateState } from './userMeInfoResponseAllocateState';
import type { UserMeInfoResponseProposalState } from './userMeInfoResponseProposalState';
import type { UserMeInfoResponseReportState } from './userMeInfoResponseReportState';
import type { UserMeInfoResponseProjectState } from './userMeInfoResponseProjectState';

export interface UserMeInfoResponse {
  id: number;
  username: string;
  fname: string;
  lname: string;
  fatherName: string;
  birth: string;
  resumeFileId?: UserMeInfoResponseResumeFileId;
  address?: UserMeInfoResponseAddress;
  phone?: UserMeInfoResponsePhone;
  active: boolean;
  userTypeId: number;
  notificationCount: number;
  allocateState: UserMeInfoResponseAllocateState;
  proposalState: UserMeInfoResponseProposalState;
  reportState: UserMeInfoResponseReportState;
  projectState: UserMeInfoResponseProjectState;
}
