/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserAddRequestResumeFileId } from './userAddRequestResumeFileId';
import type { UserAddRequestAddress } from './userAddRequestAddress';
import type { UserAddRequestPhone } from './userAddRequestPhone';

export interface UserAddRequest {
  username: string;
  password: string;
  userTypeId: number;
  fname: string;
  lname: string;
  fatherName: string;
  birth: string;
  resumeFileId?: UserAddRequestResumeFileId;
  address?: UserAddRequestAddress;
  phone?: UserAddRequestPhone;
  active: boolean;
}
