/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { UserInfoResponseResumeFileId } from './userInfoResponseResumeFileId';
import type { UserInfoResponseAddress } from './userInfoResponseAddress';
import type { UserInfoResponsePhone } from './userInfoResponsePhone';

export interface UserInfoResponse {
  id: number;
  username: string;
  fname: string;
  lname: string;
  fatherName: string;
  birth: string;
  resumeFileId?: UserInfoResponseResumeFileId;
  address?: UserInfoResponseAddress;
  phone?: UserInfoResponsePhone;
  active: boolean;
  userTypeId: number;
}
