/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  CommissionRequest,
  CommissionResponse,
  ProposalResponse,
  ReadProposalsBrokerProposalsGetParams,
  ReadProposalsBrokerProposalsLikeGetParams
} from '../../types';

import { api } from '../../axios/mutator';



  export const getBroker = () => {
/**
 * @summary Read Proposals
 */
const readProposalsBrokerProposalsGet = (
    params?: ReadProposalsBrokerProposalsGetParams,
 ) => {
      return api<ProposalResponse[]>(
      {url: `/broker/proposals/`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Read Proposals
 */
const readProposalsBrokerProposalsLikeGet = (
    params?: ReadProposalsBrokerProposalsLikeGetParams,
 ) => {
      return api<ProposalResponse[]>(
      {url: `/broker/proposals-like/`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Read Proposal
 */
const readProposalBrokerProposalsProposalIdGet = (
    proposalId: number,
 ) => {
      return api<ProposalResponse>(
      {url: `/broker/proposals/${proposalId}`, method: 'GET'
    },
      );
    }
  /**
 * @summary Add Commission
 */
const addCommissionBrokerCommissionsPost = (
    commissionRequest: CommissionRequest,
 ) => {
      return api<CommissionResponse>(
      {url: `/broker/commissions/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: commissionRequest
    },
      );
    }
  return {readProposalsBrokerProposalsGet,readProposalsBrokerProposalsLikeGet,readProposalBrokerProposalsProposalIdGet,addCommissionBrokerCommissionsPost}};
export type ReadProposalsBrokerProposalsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBroker>['readProposalsBrokerProposalsGet']>>>
export type ReadProposalsBrokerProposalsLikeGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBroker>['readProposalsBrokerProposalsLikeGet']>>>
export type ReadProposalBrokerProposalsProposalIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBroker>['readProposalBrokerProposalsProposalIdGet']>>>
export type AddCommissionBrokerCommissionsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getBroker>['addCommissionBrokerCommissionsPost']>>>
