/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetProjectMentorProjectsGetParams,
  GetReportsMentorReportsProjectIdGetParams,
  ProjectResponse,
} from '../../types';

import { api } from '../../axios/mutator';

export const getMentor = () => {
  /**
   * @summary Get Project
   */
  const getProjectMentorProjectsGet = (
    params?: GetProjectMentorProjectsGetParams
  ) => {
    return api<ProjectResponse[]>({
      url: `/mentor/projects/`,
      method: 'GET',
      params,
    });
  };
  /**
   * @summary Get Reports
   */
  const getReportsMentorReportsProjectIdGet = (
    projectId: number,
    params?: GetReportsMentorReportsProjectIdGetParams
  ) => {
    return api<unknown>({
      url: `/mentor/reports/${projectId}`,
      method: 'GET',
      params,
    });
  };
  return { getProjectMentorProjectsGet, getReportsMentorReportsProjectIdGet };
};
export type GetProjectMentorProjectsGetResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getMentor>['getProjectMentorProjectsGet']>
  >
>;
export type GetReportsMentorReportsProjectIdGetResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getMentor>['getReportsMentorReportsProjectIdGet']
    >
  >
>;
