/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetAllReportsMentorAllReportsGetParams,
  GetProjectMentorProjectsGetParams,
  GetReportsMentorReportsProjectIdGetParams,
  ProjectResponse,
} from '../../types';

import { api } from '../../axios/mutator';

export const getMentor = () => {
  /**
   * @summary Get Project
   */
  const getProjectMentorProjectsGet = (
    params?: GetProjectMentorProjectsGetParams
  ) => {
    return api<ProjectResponse[]>({
      url: `/mentor/projects/`,
      method: 'GET',
      params,
    });
  };
  /**
   * @summary Get Reports
   */
  const getReportsMentorReportsProjectIdGet = (
    projectId: number,
    params?: GetReportsMentorReportsProjectIdGetParams
  ) => {
    return api<unknown>({
      url: `/mentor/reports/${projectId}`,
      method: 'GET',
      params,
    });
  };
  /**
   * @summary Get Single Reports
   */
  const getSingleReportsMentorSingleReportReportIdGet = (reportId: number) => {
    return api<unknown>({
      url: `/mentor/single-report/${reportId}`,
      method: 'GET',
    });
  };
  /**
   * @summary Get All Reports
   */
  const getAllReportsMentorAllReportsGet = (
    params?: GetAllReportsMentorAllReportsGetParams
  ) => {
    return api<unknown>({ url: `/mentor/all-reports/`, method: 'GET', params });
  };
  return {
    getProjectMentorProjectsGet,
    getReportsMentorReportsProjectIdGet,
    getSingleReportsMentorSingleReportReportIdGet,
    getAllReportsMentorAllReportsGet,
  };
};
export type GetProjectMentorProjectsGetResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getMentor>['getProjectMentorProjectsGet']>
  >
>;
export type GetReportsMentorReportsProjectIdGetResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getMentor>['getReportsMentorReportsProjectIdGet']
    >
  >
>;
export type GetSingleReportsMentorSingleReportReportIdGetResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<
        typeof getMentor
      >['getSingleReportsMentorSingleReportReportIdGet']
    >
  >
>;
export type GetAllReportsMentorAllReportsGetResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getMentor>['getAllReportsMentorAllReportsGet']>
  >
>;
