/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type {
  ReadUsersAdminUsersGetParams,
  UserAddRequest,
  UserInfoResponse,
  UserRoleResponse
} from '../../types';

import { api } from '../../axios/mutator';



  export const getAdmin = () => {
/**
 * @summary Read User Roles
 */
const readUserRolesAdminUserRolesGet = (
    
 ) => {
      return api<UserRoleResponse[]>(
      {url: `/admin/user-roles/`, method: 'GET'
    },
      );
    }
  /**
 * @summary Create User
 */
const createUserAdminAddUserPost = (
    userAddRequest: UserAddRequest,
 ) => {
      return api<UserInfoResponse>(
      {url: `/admin/add-user/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userAddRequest
    },
      );
    }
  /**
 * @summary Update User
 */
const updateUserAdminUpdateUserUserIdPut = (
    userId: number,
    userAddRequest: UserAddRequest,
 ) => {
      return api<UserInfoResponse>(
      {url: `/admin/update-user/${userId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userAddRequest
    },
      );
    }
  /**
 * @summary Update User
 */
const updateUserAdminDeleteUserUserIdDelete = (
    userId: number,
 ) => {
      return api<UserInfoResponse>(
      {url: `/admin/delete-user/${userId}`, method: 'DELETE'
    },
      );
    }
  /**
 * @summary Read Users
 */
const readUsersAdminUsersGet = (
    params?: ReadUsersAdminUsersGetParams,
 ) => {
      return api<UserInfoResponse[]>(
      {url: `/admin/users/`, method: 'GET',
        params
    },
      );
    }
  return {readUserRolesAdminUserRolesGet,createUserAdminAddUserPost,updateUserAdminUpdateUserUserIdPut,updateUserAdminDeleteUserUserIdDelete,readUsersAdminUsersGet}};
export type ReadUserRolesAdminUserRolesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['readUserRolesAdminUserRolesGet']>>>
export type CreateUserAdminAddUserPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['createUserAdminAddUserPost']>>>
export type UpdateUserAdminUpdateUserUserIdPutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['updateUserAdminUpdateUserUserIdPut']>>>
export type UpdateUserAdminDeleteUserUserIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['updateUserAdminDeleteUserUserIdDelete']>>>
export type ReadUsersAdminUsersGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAdmin>['readUsersAdminUsersGet']>>>
